#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# If there are whitespace errors, print the offending file names and fail.

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.(h|c|cpp)$") || true)

if [ ! -z "${files}" ]; then
    for src in $files ; do
      clang-format -i $REPO_ROOT_DIR/$src
    done
    git add $(echo "$files" | paste -s -d " " -)
fi
